name: Deploy to FTP

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v2

    - name: Deploy to FTP server
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        server: "nt15.unoeuro.com"
        username: "luckfish.dk"
        password: "Ady9aGrFbthx4km5wceD"
        local-dir: ./  
        server-dir: /public_html/