name: Deploy to FTP

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository content
      uses: actions/checkout@v2

    - name: Build the project
      run: |
       
        npm install
        npm run build

    - name: Deploy to FTP server
      uses: SamKirkland/FTP-Deploy-Action@4.3.0
      with:
        ftp-server: ${{FTP.FTP_SERVER}}
        ftp-username: ${{FTP.FTP_USERNAME}}
        ftp-password: ${{FTP.FTP_PASSWORD}}
        local-dir: ./  
        server-dir: /public_html/  